<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class CountrySeeder extends Seeder
{
	public function run()
	{
		$model = model('CountryModel');

    $data = [
      [
        'name' => 'Afeganistão',
        'initials' => 'AF',
        'initials3' => 'AFG',
        'code' => '004',
      ],
      [
        'name' => 'África do Sul',
        'initials' => 'ZA',
        'initials3' => 'ZAF',
        'code' => '710',
      ],
      [
        'name' => 'Albânia',
        'initials' => 'AL',
        'initials3' => 'ALB',
        'code' => '008',
      ],
      [
        'name' => 'Alemanha',
        'initials' => 'DE',
        'initials3' => 'DEU',
        'code' => '276',
      ],
      [
        'name' => 'Andorra',
        'initials' => 'AD',
        'initials3' => 'AND',
        'code' => '020',
      ],
      [
        'name' => 'Angola',
        'initials' => 'AO',
        'initials3' => 'AGO',
        'code' => '024',
      ],
      [
        'name' => 'Anguilla',
        'initials' => 'AI',
        'initials3' => 'AIA',
        'code' => '660',
      ],
      [
        'name' => 'Antártida',
        'initials' => 'AQ',
        'initials3' => 'ATA',
        'code' => '010',
      ],
      [
        'name' => 'Antígua e Barbuda',
        'initials' => 'AG',
        'initials3' => 'ATG',
        'code' => '028',
      ],
      [
        'name' => 'Antilhas Holandesas',
        'initials' => 'AN',
        'initials3' => 'ANT',
        'code' => '530',
      ],
      [
        'name' => 'Arábia Saudita',
        'initials' => 'SA',
        'initials3' => 'SAU',
        'code' => '682',
      ],
      [
        'name' => 'Argélia',
        'initials' => 'DZ',
        'initials3' => 'DZA',
        'code' => '012',
      ],
      [
        'name' => 'Argentina',
        'initials' => 'AR',
        'initials3' => 'ARG',
        'code' => '032',
      ],
      [
        'name' => 'Armênia',
        'initials' => 'AM',
        'initials3' => 'ARM',
        'code' => '51',
      ],
      [
        'name' => 'Aruba',
        'initials' => 'AW',
        'initials3' => 'ABW',
        'code' => '533',
      ],
      [
        'name' => 'Austrália',
        'initials' => 'AU',
        'initials3' => 'AUS',
        'code' => '036',
      ],
      [
        'name' => 'Áustria',
        'initials' => 'AT',
        'initials3' => 'AUT',
        'code' => '040',
      ],
      [
        'name' => 'Azerbaijão',
        'initials' => 'AZ  ',
        'initials3' => 'AZE',
        'code' => '31',
      ],
      [
        'name' => 'Bahamas',
        'initials' => 'BS',
        'initials3' => 'BHS',
        'code' => '044',
      ],
      [
        'name' => 'Bahrein',
        'initials' => 'BH',
        'initials3' => 'BHR',
        'code' => '048',
      ],
      [
        'name' => 'Bangladesh',
        'initials' => 'BD',
        'initials3' => 'BGD',
        'code' => '050',
      ],
      [
        'name' => 'Barbados',
        'initials' => 'BB',
        'initials3' => 'BRB',
        'code' => '052',
      ],
      [
        'name' => 'Belarus',
        'initials' => 'BY',
        'initials3' => 'BLR',
        'code' => '112',
      ],
      [
        'name' => 'Bélgica',
        'initials' => 'BE',
        'initials3' => 'BEL',
        'code' => '056',
      ],
      [
        'name' => 'Belize',
        'initials' => 'BZ',
        'initials3' => 'BLZ',
        'code' => '084',
      ],
      [
        'name' => 'Benin',
        'initials' => 'BJ',
        'initials3' => 'BEN',
        'code' => '204',
      ],
      [
        'name' => 'Bermudas',
        'initials' => 'BM',
        'initials3' => 'BMU',
        'code' => '060',
      ],
      [
        'name' => 'Bolívia',
        'initials' => 'BO',
        'initials3' => 'BOL',
        'code' => '068',
      ],
      [
        'name' => 'Bósnia-Herzegóvina',
        'initials' => 'BA',
        'initials3' => 'BIH',
        'code' => '070',
      ],
      [
        'name' => 'Botsuana',
        'initials' => 'BW',
        'initials3' => 'BWA',
        'code' => '072',
      ],
      [
        'name' => 'Brasil',
        'initials' => 'BR',
        'initials3' => 'BRA',
        'code' => '076',
      ],
      [
        'name' => 'Brunei',
        'initials' => 'BN',
        'initials3' => 'BRN',
        'code' => '096',
      ],
      [
        'name' => 'Bulgária',
        'initials' => 'BG',
        'initials3' => 'BGR',
        'code' => '100',
      ],
      [
        'name' => 'Burkina Fasso',
        'initials' => 'BF',
        'initials3' => 'BFA',
        'code' => '854',
      ],
      [
        'name' => 'Burundi',
        'initials' => 'BI',
        'initials3' => 'BDI',
        'code' => '108',
      ],
      [
        'name' => 'Butão',
        'initials' => 'BT',
        'initials3' => 'BTN',
        'code' => '064',
      ],
      [
        'name' => 'Cabo Verde',
        'initials' => 'CV',
        'initials3' => 'CPV',
        'code' => '132',
      ],
      [
        'name' => 'Camarões',
        'initials' => 'CM',
        'initials3' => 'CMR',
        'code' => '120',
      ],
      [
        'name' => 'Camboja',
        'initials' => 'KH',
        'initials3' => 'KHM',
        'code' => '116',
      ],
      [
        'name' => 'Canadá',
        'initials' => 'CA',
        'initials3' => 'CAN',
        'code' => '124',
      ],
      [
        'name' => 'Cazaquistão',
        'initials' => 'KZ',
        'initials3' => 'KAZ',
        'code' => '398',
      ],
      [
        'name' => 'Chade',
        'initials' => 'TD',
        'initials3' => 'TCD',
        'code' => '148',
      ],
      [
        'name' => 'Chile',
        'initials' => 'CL',
        'initials3' => 'CHL',
        'code' => '152',
      ],
      [
        'name' => 'China',
        'initials' => 'CN',
        'initials3' => 'CHN',
        'code' => '156',
      ],
      [
        'name' => 'Chipre',
        'initials' => 'CY',
        'initials3' => 'CYP',
        'code' => '196',
      ],
      [
        'name' => 'Cingapura',
        'initials' => 'SG',
        'initials3' => 'SGP',
        'code' => '702',
      ],
      [
        'name' => 'Colômbia',
        'initials' => 'CO',
        'initials3' => 'COL',
        'code' => '170',
      ],
      [
        'name' => 'Congo',
        'initials' => 'CG',
        'initials3' => 'COG',
        'code' => '178',
      ],
      [
        'name' => 'Coréia do Norte',
        'initials' => 'KP',
        'initials3' => 'PRK',
        'code' => '408',
      ],
      [
        'name' => 'Coréia do Sul',
        'initials' => 'KR',
        'initials3' => 'KOR',
        'code' => '410',
      ],
      [
        'name' => 'Costa do Marfim',
        'initials' => 'CI',
        'initials3' => 'CIV',
        'code' => '384',
      ],
      [
        'name' => 'Costa Rica',
        'initials' => 'CR',
        'initials3' => 'CRI',
        'code' => '188',
      ],
      [
        'name' => 'Croácia (Hrvatska)',
        'initials' => 'HR',
        'initials3' => 'HRV',
        'code' => '191',
      ],
      [
        'name' => 'Cuba',
        'initials' => 'CU',
        'initials3' => 'CUB',
        'code' => '192',
      ],
      [
        'name' => 'Dinamarca',
        'initials' => 'DK',
        'initials3' => 'DNK',
        'code' => '208',
      ],
      [
        'name' => 'Djibuti',
        'initials' => 'DJ',
        'initials3' => 'DJI',
        'code' => '262',
      ],
      [
        'name' => 'Dominica',
        'initials' => 'DM',
        'initials3' => 'DMA',
        'code' => '212',
      ],
      [
        'name' => 'Egito',
        'initials' => 'EG',
        'initials3' => 'EGY',
        'code' => '818',
      ],
      [
        'name' => 'El Salvador',
        'initials' => 'SV',
        'initials3' => 'SLV',
        'code' => '222',
      ],
      [
        'name' => 'Emirados Árabes Unidos',
        'initials' => 'AE',
        'initials3' => 'ARE',
        'code' => '784',
      ],
      [
        'name' => 'Equador',
        'initials' => 'EC',
        'initials3' => 'ECU',
        'code' => '218',
      ],
      [
        'name' => 'Eritréia',
        'initials' => 'ER',
        'initials3' => 'ERI',
        'code' => '232',
      ],
      [
        'name' => 'Eslováquia',
        'initials' => 'SK',
        'initials3' => 'SVK',
        'code' => '703',
      ],
      [
        'name' => 'Eslovênia',
        'initials' => 'SI',
        'initials3' => 'SVN',
        'code' => '705',
      ],
      [
        'name' => 'Espanha',
        'initials' => 'ES',
        'initials3' => 'ESP',
        'code' => '724',
      ],
      [
        'name' => 'Estados Unidos',
        'initials' => 'US',
        'initials3' => 'USA',
        'code' => '840',
      ],
      [
        'name' => 'Estônia',
        'initials' => 'EE',
        'initials3' => 'EST',
        'code' => '233',
      ],
      [
        'name' => 'Etiópia',
        'initials' => 'ET',
        'initials3' => 'ETH',
        'code' => '231',
      ],
      [
        'name' => 'Fiji',
        'initials' => 'FJ',
        'initials3' => 'FJI',
        'code' => '242',
      ],
      [
        'name' => 'Filipinas',
        'initials' => 'PH',
        'initials3' => 'PHL',
        'code' => '608',
      ],
      [
        'name' => 'Finlândia',
        'initials' => 'FI',
        'initials3' => 'FIN',
        'code' => '246',
      ],
      [
        'name' => 'França',
        'initials' => 'FR',
        'initials3' => 'FRA',
        'code' => '250',
      ],
      [
        'name' => 'Gabão',
        'initials' => 'GA',
        'initials3' => 'GAB',
        'code' => '266',
      ],
      [
        'name' => 'Gâmbia',
        'initials' => 'GM',
        'initials3' => 'GMB',
        'code' => '270',
      ],
      [
        'name' => 'Gana',
        'initials' => 'GH',
        'initials3' => 'GHA',
        'code' => '288',
      ],
      [
        'name' => 'Geórgia',
        'initials' => 'GE',
        'initials3' => 'GEO',
        'code' => '268',
      ],
      [
        'name' => 'Gibraltar',
        'initials' => 'GI',
        'initials3' => 'GIB',
        'code' => '292',
      ],
      [
        'name' => 'Grã-Bretanha (Reino Unido, UK)',
        'initials' => 'GB',
        'initials3' => 'GBR',
        'code' => '826',
      ],
      [
        'name' => 'Granada',
        'initials' => 'GD',
        'initials3' => 'GRD',
        'code' => '308',
      ],
      [
        'name' => 'Grécia',
        'initials' => 'GR',
        'initials3' => 'GRC',
        'code' => '300',
      ],
      [
        'name' => 'Groelândia',
        'initials' => 'GL',
        'initials3' => 'GRL',
        'code' => '304',
      ],
      [
        'name' => 'Guadalupe',
        'initials' => 'GP',
        'initials3' => 'GLP',
        'code' => '312',
      ],
      [
        'name' => 'Guam (Território dos Estados Unidos)',
        'initials' => 'GU',
        'initials3' => 'GUM',
        'code' => '316',
      ],
      [
        'name' => 'Guatemala',
        'initials' => 'GT',
        'initials3' => 'GTM',
        'code' => '320',
      ],
      [
        'name' => 'Guernsey',
        'initials' => 'G',
        'initials3' => 'GGY',
        'code' => '832',
      ],
      [
        'name' => 'Guiana',
        'initials' => 'GY',
        'initials3' => 'GUY',
        'code' => '328',
      ],
      [
        'name' => 'Guiana Francesa',
        'initials' => 'GF',
        'initials3' => 'GUF',
        'code' => '254',
      ],
      [
        'name' => 'Guiné',
        'initials' => 'GN',
        'initials3' => 'GIN',
        'code' => '324',
      ],
      [
        'name' => 'Guiné Equatorial',
        'initials' => 'GQ',
        'initials3' => 'GNQ',
        'code' => '226',
      ],
      [
        'name' => 'Guiné-Bissau',
        'initials' => 'GW',
        'initials3' => 'GNB',
        'code' => '624',
      ],
      [
        'name' => 'Haiti',
        'initials' => 'HT',
        'initials3' => 'HTI',
        'code' => '332',
      ],
      [
        'name' => 'Holanda',
        'initials' => 'NL',
        'initials3' => 'NLD',
        'code' => '528',
      ],
      [
        'name' => 'Honduras',
        'initials' => 'HN',
        'initials3' => 'HND',
        'code' => '340',
      ],
      [
        'name' => 'Hong Kong',
        'initials' => 'HK',
        'initials3' => 'HKG',
        'code' => '344',
      ],
      [
        'name' => 'Hungria',
        'initials' => 'HU',
        'initials3' => 'HUN',
        'code' => '348',
      ],
      [
        'name' => 'Iêmen',
        'initials' => 'YE',
        'initials3' => 'YEM',
        'code' => '887',
      ],
      [
        'name' => 'Ilha Bouvet (Território da Noruega)',
        'initials' => 'BV',
        'initials3' => 'BVT',
        'code' => '074',
      ],
      [
        'name' => 'Ilha do Homem',
        'initials' => 'IM',
        'initials3' => 'IMN',
        'code' => '833',
      ],
      [
        'name' => 'Ilha Natal',
        'initials' => 'CX',
        'initials3' => 'CXR',
        'code' => '162',
      ],
      [
        'name' => 'Ilha Pitcairn',
        'initials' => 'PN',
        'initials3' => 'PCN',
        'code' => '612',
      ],
      [
        'name' => 'Ilha Reunião',
        'initials' => 'RE',
        'initials3' => 'REU',
        'code' => '638',
      ],
      [
        'name' => 'Ilhas Aland',
        'initials' => 'AX',
        'initials3' => 'ALA',
        'code' => '248',
      ],
      [
        'name' => 'Ilhas Cayman',
        'initials' => 'KY',
        'initials3' => 'CYM',
        'code' => '136',
      ],
      [
        'name' => 'Ilhas Cocos',
        'initials' => 'CC',
        'initials3' => 'CCK',
        'code' => '166',
      ],
      [
        'name' => 'Ilhas Comores',
        'initials' => 'KM',
        'initials3' => 'COM',
        'code' => '174',
      ],
      [
        'name' => 'Ilhas Cook',
        'initials' => 'CK',
        'initials3' => 'COK',
        'code' => '184',
      ],
      [
        'name' => 'Ilhas Faroes',
        'initials' => 'FO',
        'initials3' => 'FRO',
        'code' => '234',
      ],
      [
        'name' => 'Ilhas Falkland (Malvinas)',
        'initials' => 'FK',
        'initials3' => 'FLK',
        'code' => '238',
      ],
      [
        'name' => 'Ilhas Geórgia do Sul e Sandwich do Sul',
        'initials' => 'GS',
        'initials3' => 'SGS',
        'code' => '239',
      ],
      [
        'name' => 'Ilhas Heard e McDonald (Território da Austrália)',
        'initials' => 'HM',
        'initials3' => 'HMD',
        'code' => '334',
      ],
      [
        'name' => 'Ilhas Marianas do Norte',
        'initials' => 'MP',
        'initials3' => 'MNP',
        'code' => '580',
      ],
      [
        'name' => 'Ilhas Marshall',
        'initials' => 'MH',
        'initials3' => 'MHL',
        'code' => '584',
      ],
      [
        'name' => 'Ilhas Menores dos Estados Unidos',
        'initials' => 'UM',
        'initials3' => 'UMI',
        'code' => '581',
      ],
      [
        'name' => 'Ilhas Norfolk',
        'initials' => 'NF',
        'initials3' => 'NFK',
        'code' => '574',
      ],
      [
        'name' => 'Ilhas Seychelles',
        'initials' => 'SC',
        'initials3' => 'SYC',
        'code' => '690',
      ],
      [
        'name' => 'Ilhas Solomão',
        'initials' => 'SB',
        'initials3' => 'SLB',
        'code' => '090',
      ],
      [
        'name' => 'Ilhas Svalbard e Jan Mayen',
        'initials' => 'SJ',
        'initials3' => 'SJM',
        'code' => '744',
      ],
      [
        'name' => 'Ilhas Tokelau',
        'initials' => 'TK',
        'initials3' => 'TKL',
        'code' => '772',
      ],
      [
        'name' => 'Ilhas Turks e Caicos',
        'initials' => 'TC',
        'initials3' => 'TCA',
        'code' => '796',
      ],
      [
        'name' => 'Ilhas Virgens (Estados Unidos)',
        'initials' => 'VI',
        'initials3' => 'VIR',
        'code' => '850',
      ],
      [
        'name' => 'Ilhas Virgens (Inglaterra)',
        'initials' => 'VG',
        'initials3' => 'VGB',
        'code' => '092',
      ],
      [
        'name' => 'Ilhas Wallis e Futuna',
        'initials' => 'WF',
        'initials3' => 'WLF',
        'code' => '876',
      ],
      [
        'name' => 'índia',
        'initials' => 'IN',
        'initials3' => 'IND',
        'code' => '356',
      ],
      [
        'name' => 'Indonésia',
        'initials' => 'ID',
        'initials3' => 'IDN',
        'code' => '360',
      ],
      [
        'name' => 'Irã',
        'initials' => 'IR',
        'initials3' => 'IRN',
        'code' => '364',
      ],
      [
        'name' => 'Iraque',
        'initials' => 'IQ',
        'initials3' => 'IRQ',
        'code' => '368',
      ],
      [
        'name' => 'Irlanda',
        'initials' => 'IE',
        'initials3' => 'IRL',
        'code' => '372',
      ],
      [
        'name' => 'Islândia',
        'initials' => 'IS',
        'initials3' => 'ISL',
        'code' => '352',
      ],
      [
        'name' => 'Israel',
        'initials' => 'IL',
        'initials3' => 'ISR',
        'code' => '376',
      ],
      [
        'name' => 'Itália',
        'initials' => 'IT',
        'initials3' => 'ITA',
        'code' => '380',
      ],
      [
        'name' => 'Jamaica',
        'initials' => 'JM',
        'initials3' => 'JAM',
        'code' => '388',
      ],
      [
        'name' => 'Japão',
        'initials' => 'JP',
        'initials3' => 'JPN',
        'code' => '392',
      ],
      [
        'name' => 'Jersey',
        'initials' => 'JE',
        'initials3' => 'JEY',
        'code' => '832',
      ],
      [
        'name' => 'Jordânia',
        'initials' => 'JO',
        'initials3' => 'JOR',
        'code' => '400',
      ],
      [
        'name' => 'Kênia',
        'initials' => 'KE',
        'initials3' => 'KEN',
        'code' => '404',
      ],
      [
        'name' => 'Kiribati',
        'initials' => 'KI',
        'initials3' => 'KIR',
        'code' => '296',
      ],
      [
        'name' => 'Kuait',
        'initials' => 'KW',
        'initials3' => 'KWT',
        'code' => '414',
      ],
      [
        'name' => 'Laos',
        'initials' => 'LA',
        'initials3' => 'LAO',
        'code' => '418',
      ],
      [
        'name' => 'Látvia',
        'initials' => 'LV',
        'initials3' => 'LVA',
        'code' => '428',
      ],
      [
        'name' => 'Lesoto',
        'initials' => 'LS',
        'initials3' => 'LSO',
        'code' => '426',
      ],
      [
        'name' => 'Líbano',
        'initials' => 'LB',
        'initials3' => 'LBN',
        'code' => '422',
      ],
      [
        'name' => 'Libéria',
        'initials' => 'LR',
        'initials3' => 'LBR',
        'code' => '430',
      ],
      [
        'name' => 'Líbia',
        'initials' => 'LY',
        'initials3' => 'LBY',
        'code' => '434',
      ],
      [
        'name' => 'Liechtenstein',
        'initials' => 'LI',
        'initials3' => 'LIE',
        'code' => '438',
      ],
      [
        'name' => 'Lituânia',
        'initials' => 'LT',
        'initials3' => 'LTU',
        'code' => '440',
      ],
      [
        'name' => 'Luxemburgo',
        'initials' => 'LU',
        'initials3' => 'LUX',
        'code' => '442',
      ],
      [
        'name' => 'Macau',
        'initials' => 'MO',
        'initials3' => 'MAC',
        'code' => '446',
      ],
      [
        'name' => 'Macedônia (República Yugoslava)',
        'initials' => 'MK',
        'initials3' => 'MKD',
        'code' => '807',
      ],
      [
        'name' => 'Madagascar',
        'initials' => 'MG',
        'initials3' => 'MDG',
        'code' => '450',
      ],
      [
        'name' => 'Malásia',
        'initials' => 'MY',
        'initials3' => 'MYS',
        'code' => '458',
      ],
      [
        'name' => 'Malaui',
        'initials' => 'MW',
        'initials3' => 'MWI',
        'code' => '454',
      ],
      [
        'name' => 'Maldivas',
        'initials' => 'MV',
        'initials3' => 'MDV',
        'code' => '462',
      ],
      [
        'name' => 'Mali',
        'initials' => 'ML',
        'initials3' => 'MLI',
        'code' => '466',
      ],
      [
        'name' => 'Malta',
        'initials' => 'MT',
        'initials3' => 'MLT',
        'code' => '470',
      ],
      [
        'name' => 'Marrocos',
        'initials' => 'MA',
        'initials3' => 'MAR',
        'code' => '504',
      ],
      [
        'name' => 'Martinica',
        'initials' => 'MQ',
        'initials3' => 'MTQ',
        'code' => '474',
      ],
      [
        'name' => 'Maurício',
        'initials' => 'MU',
        'initials3' => 'MUS',
        'code' => '480',
      ],
      [
        'name' => 'Mauritânia',
        'initials' => 'MR',
        'initials3' => 'MRT',
        'code' => '478',
      ],
      [
        'name' => 'Mayotte',
        'initials' => 'YT',
        'initials3' => 'MYT',
        'code' => '175',
      ],
      [
        'name' => 'México',
        'initials' => 'MX',
        'initials3' => 'MEX',
        'code' => '484',
      ],
      [
        'name' => 'Micronésia',
        'initials' => 'FM',
        'initials3' => 'FSM',
        'code' => '583',
      ],
      [
        'name' => 'Moçambique',
        'initials' => 'MZ',
        'initials3' => 'MOZ',
        'code' => '508',
      ],
      [
        'name' => 'Moldova',
        'initials' => 'MD',
        'initials3' => 'MDA',
        'code' => '498',
      ],
      [
        'name' => 'Mônaco',
        'initials' => 'MC',
        'initials3' => 'MCO',
        'code' => '492',
      ],
      [
        'name' => 'Mongólia',
        'initials' => 'MN',
        'initials3' => 'MNG',
        'code' => '496',
      ],
      [
        'name' => 'Montenegro',
        'initials' => 'ME',
        'initials3' => 'MNE',
        'code' => '499',
      ],
      [
        'name' => 'Montserrat',
        'initials' => 'MS',
        'initials3' => 'MSR',
        'code' => '500',
      ],
      [
        'name' => 'Myanma',
        'initials' => 'MM',
        'initials3' => 'MMR',
        'code' => '104',
      ],
      [
        'name' => 'Namíbia',
        'initials' => 'NA',
        'initials3' => 'NAM',
        'code' => '516',
      ],
      [
        'name' => 'Nauru',
        'initials' => 'NR',
        'initials3' => 'NRU',
        'code' => '520',
      ],
      [
        'name' => 'Nepal',
        'initials' => 'NP',
        'initials3' => 'NPL',
        'code' => '524',
      ],
      [
        'name' => 'Nicarágua',
        'initials' => 'NI',
        'initials3' => 'NIC',
        'code' => '558',
      ],
      [
        'name' => 'Níger',
        'initials' => 'NE',
        'initials3' => 'NER',
        'code' => '562',
      ],
      [
        'name' => 'Nigéria',
        'initials' => 'NG',
        'initials3' => 'NGA',
        'code' => '566',
      ],
      [
        'name' => 'Niue',
        'initials' => 'NU',
        'initials3' => 'NIU',
        'code' => '570',
      ],
      [
        'name' => 'Noruega',
        'initials' => 'NO',
        'initials3' => 'NOR',
        'code' => '578',
      ],
      [
        'name' => 'Nova Caledônia',
        'initials' => 'NC',
        'initials3' => 'NCL',
        'code' => '540',
      ],
      [
        'name' => 'Nova Zelândia',
        'initials' => 'NZ',
        'initials3' => 'NZL',
        'code' => '554',
      ],
      [
        'name' => 'Omã',
        'initials' => 'OM',
        'initials3' => 'OMN',
        'code' => '512',
      ],
      [
        'name' => 'Palau',
        'initials' => 'PW',
        'initials3' => 'PLW',
        'code' => '585',
      ],
      [
        'name' => 'Panamá',
        'initials' => 'PA',
        'initials3' => 'PAN',
        'code' => '591',
      ],
      [
        'name' => 'Papua-Nova Guiné',
        'initials' => 'PG',
        'initials3' => 'PNG',
        'code' => '598',
      ],
      [
        'name' => 'Paquistão',
        'initials' => 'PK',
        'initials3' => 'PAK',
        'code' => '586',
      ],
      [
        'name' => 'Paraguai',
        'initials' => 'PY',
        'initials3' => 'PRY',
        'code' => '600',
      ],
      [
        'name' => 'Peru',
        'initials' => 'PE',
        'initials3' => 'PER',
        'code' => '604',
      ],
      [
        'name' => 'Polinésia Francesa',
        'initials' => 'PF',
        'initials3' => 'PYF',
        'code' => '258',
      ],
      [
        'name' => 'Polônia',
        'initials' => 'PL',
        'initials3' => 'POL',
        'code' => '616',
      ],
      [
        'name' => 'Porto Rico',
        'initials' => 'PR',
        'initials3' => 'PRI',
        'code' => '630',
      ],
      [
        'name' => 'Portugal',
        'initials' => 'PT',
        'initials3' => 'PRT',
        'code' => '620',
      ],
      [
        'name' => 'Qatar',
        'initials' => 'QA',
        'initials3' => 'QAT',
        'code' => '634',
      ],
      [
        'name' => 'Quirguistão',
        'initials' => 'KG',
        'initials3' => 'KGZ',
        'code' => '417',
      ],
      [
        'name' => 'República Centro-Africana',
        'initials' => 'CF',
        'initials3' => 'CAF',
        'code' => '140',
      ],
      [
        'name' => 'República Democrática do Congo',
        'initials' => 'CD',
        'initials3' => 'COD',
        'code' => '180',
      ],
      [
        'name' => 'República Dominicana',
        'initials' => 'DO',
        'initials3' => 'DOM',
        'code' => '214',
      ],
      [
        'name' => 'República Tcheca',
        'initials' => 'CZ',
        'initials3' => 'CZE',
        'code' => '203',
      ],
      [
        'name' => 'Romênia',
        'initials' => 'RO',
        'initials3' => 'ROM',
        'code' => '642',
      ],
      [
        'name' => 'Ruanda',
        'initials' => 'RW',
        'initials3' => 'RWA',
        'code' => '646',
      ],
      [
        'name' => 'Rússia (antiga URSS) - Federação Russa',
        'initials' => 'RU',
        'initials3' => 'RUS',
        'code' => '643',
      ],
      [
        'name' => 'Saara Ocidental',
        'initials' => 'EH',
        'initials3' => 'ESH',
        'code' => '732',
      ],
      [
        'name' => 'Saint Vincente e Granadinas',
        'initials' => 'VC',
        'initials3' => 'VCT',
        'code' => '670',
      ],
      [
        'name' => 'Samoa Americana',
        'initials' => 'AS',
        'initials3' => 'ASM',
        'code' => '016',
      ],
      [
        'name' => 'Samoa Ocidental',
        'initials' => 'WS',
        'initials3' => 'WSM',
        'code' => '882',
      ],
      [
        'name' => 'San Marino',
        'initials' => 'SM',
        'initials3' => 'SMR',
        'code' => '674',
      ],
      [
        'name' => 'Santa Helena',
        'initials' => 'SH',
        'initials3' => 'SHN',
        'code' => '654',
      ],
      [
        'name' => 'Santa Lúcia',
        'initials' => 'LC',
        'initials3' => 'LCA',
        'code' => '662',
      ],
      [
        'name' => 'São Bartolomeu',
        'initials' => 'BL',
        'initials3' => 'BLM',
        'code' => '652',
      ],
      [
        'name' => 'São Cristóvão e Névis',
        'initials' => 'KN',
        'initials3' => 'KNA',
        'code' => '659',
      ],
      [
        'name' => 'São Martim',
        'initials' => 'MF',
        'initials3' => 'MAF',
        'code' => '663',
      ],
      [
        'name' => 'São Tomé e Príncipe',
        'initials' => 'ST',
        'initials3' => 'STP',
        'code' => '678',
      ],
      [
        'name' => 'Senegal',
        'initials' => 'SN',
        'initials3' => 'SEN',
        'code' => '686',
      ],
      [
        'name' => 'Serra Leoa',
        'initials' => 'SL',
        'initials3' => 'SLE',
        'code' => '694',
      ],
      [
        'name' => 'Sérvia',
        'initials' => 'RS',
        'initials3' => 'SRB',
        'code' => '688',
      ],
      [
        'name' => 'Síria',
        'initials' => 'SY',
        'initials3' => 'SYR',
        'code' => '760',
      ],
      [
        'name' => 'Somália',
        'initials' => 'SO',
        'initials3' => 'SOM',
        'code' => '706',
      ],
      [
        'name' => 'Sri Lanka',
        'initials' => 'LK',
        'initials3' => 'LKA',
        'code' => '144',
      ],
      [
        'name' => 'St. Pierre and Miquelon',
        'initials' => 'PM',
        'initials3' => 'SPM',
        'code' => '666',
      ],
      [
        'name' => 'Suazilândia',
        'initials' => 'SZ',
        'initials3' => 'SWZ',
        'code' => '748',
      ],
      [
        'name' => 'Sudão',
        'initials' => 'SD',
        'initials3' => 'SDN',
        'code' => '736',
      ],
      [
        'name' => 'Suécia',
        'initials' => 'SE',
        'initials3' => 'SWE',
        'code' => '752',
      ],
      [
        'name' => 'Suíça',
        'initials' => 'CH',
        'initials3' => 'CHE',
        'code' => '756',
      ],
      [
        'name' => 'Suriname',
        'initials' => 'SR',
        'initials3' => 'SUR',
        'code' => '740',
      ],
      [
        'name' => 'Tadjiquistão',
        'initials' => 'TJ',
        'initials3' => 'TJK',
        'code' => '762',
      ],
      [
        'name' => 'Tailândia',
        'initials' => 'TH',
        'initials3' => 'THA',
        'code' => '764',
      ],
      [
        'name' => 'Taiwan',
        'initials' => 'TW',
        'initials3' => 'TWN',
        'code' => '158',
      ],
      [
        'name' => 'Tanzânia',
        'initials' => 'TZ',
        'initials3' => 'TZA',
        'code' => '834',
      ],
      [
        'name' => 'Território Britânico do Oceano índico',
        'initials' => 'IO',
        'initials3' => 'IOT',
        'code' => '086',
      ],
      [
        'name' => 'Territórios do Sul da França',
        'initials' => 'TF',
        'initials3' => 'ATF',
        'code' => '260',
      ],
      [
        'name' => 'Territórios Palestinos Ocupados',
        'initials' => 'PS',
        'initials3' => 'PSE',
        'code' => '275',
      ],
      [
        'name' => 'Timor Leste',
        'initials' => 'TP',
        'initials3' => 'TMP',
        'code' => '626',
      ],
      [
        'name' => 'Togo',
        'initials' => 'TG',
        'initials3' => 'TGO',
        'code' => '768',
      ],
      [
        'name' => 'Tonga',
        'initials' => 'TO',
        'initials3' => 'TON',
        'code' => '776',
      ],
      [
        'name' => 'Trinidad and Tobago',
        'initials' => 'TT',
        'initials3' => 'TTO',
        'code' => '780',
      ],
      [
        'name' => 'Tunísia',
        'initials' => 'TN',
        'initials3' => 'TUN',
        'code' => '788',
      ],
      [
        'name' => 'Turcomenistão',
        'initials' => 'TM',
        'initials3' => 'TKM',
        'code' => '795',
      ],
      [
        'name' => 'Turquia',
        'initials' => 'TR',
        'initials3' => 'TUR',
        'code' => '792',
      ],
      [
        'name' => 'Tuvalu',
        'initials' => 'TV',
        'initials3' => 'TUV',
        'code' => '798',
      ],
      [
        'name' => 'Ucrânia',
        'initials' => 'UA',
        'initials3' => 'UKR',
        'code' => '804',
      ],
      [
        'name' => 'Uganda',
        'initials' => 'UG',
        'initials3' => 'UGA',
        'code' => '800',
      ],
      [
        'name' => 'Uruguai',
        'initials' => 'UY',
        'initials3' => 'URY',
        'code' => '858',
      ],
      [
        'name' => 'Uzbequistão',
        'initials' => 'UZ',
        'initials3' => 'UZB',
        'code' => '860',
      ],
      [
        'name' => 'Vanuatu',
        'initials' => 'VU',
        'initials3' => 'VUT',
        'code' => '548',
      ],
      [
        'name' => 'Vaticano',
        'initials' => 'VA',
        'initials3' => 'VAT',
        'code' => '336',
      ],
      [
        'name' => 'Venezuela',
        'initials' => 'VE',
        'initials3' => 'VEN',
        'code' => '862',
      ],
      [
        'name' => 'Vietnã',
        'initials' => 'VN',
        'initials3' => 'VNM',
        'code' => '704',
      ],
      [
        'name' => 'Zâmbia',
        'initials' => 'ZM',
        'initials3' => 'ZMB',
        'code' => '894',
      ],
      [
        'name' => 'Zimbábue',
        'initials' => 'ZW',
        'initials3' => 'ZWE',
        'code' => '716',
      ],
    ];

    $model->insertBatch($data);
	}
}
