<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class CountrySeeder extends Seeder
{
    public function run()
    {
        $model = model('CountryModel');

        $data = [
            [
                'name' => 'Afeganistão',
                'initials' => 'AF',
                'initials_three' => 'AFG',
                'code' => '004',
            ],
            [
                'name' => 'África do Sul',
                'initials' => 'ZA',
                'initials_three' => 'ZAF',
                'code' => '710',
            ],
            [
                'name' => 'Albânia',
                'initials' => 'AL',
                'initials_three' => 'ALB',
                'code' => '008',
            ],
            [
                'name' => 'Alemanha',
                'initials' => 'DE',
                'initials_three' => 'DEU',
                'code' => '276',
            ],
            [
                'name' => 'Andorra',
                'initials' => 'AD',
                'initials_three' => 'AND',
                'code' => '020',
            ],
            [
                'name' => 'Angola',
                'initials' => 'AO',
                'initials_three' => 'AGO',
                'code' => '024',
            ],
            [
                'name' => 'Anguilla',
                'initials' => 'AI',
                'initials_three' => 'AIA',
                'code' => '660',
            ],
            [
                'name' => 'Antártida',
                'initials' => 'AQ',
                'initials_three' => 'ATA',
                'code' => '010',
            ],
            [
                'name' => 'Antígua e Barbuda',
                'initials' => 'AG',
                'initials_three' => 'ATG',
                'code' => '028',
            ],
            [
                'name' => 'Antilhas Holandesas',
                'initials' => 'AN',
                'initials_three' => 'ANT',
                'code' => '530',
            ],
            [
                'name' => 'Arábia Saudita',
                'initials' => 'SA',
                'initials_three' => 'SAU',
                'code' => '682',
            ],
            [
                'name' => 'Argélia',
                'initials' => 'DZ',
                'initials_three' => 'DZA',
                'code' => '012',
            ],
            [
                'name' => 'Argentina',
                'initials' => 'AR',
                'initials_three' => 'ARG',
                'code' => '032',
            ],
            [
                'name' => 'Armênia',
                'initials' => 'AM',
                'initials_three' => 'ARM',
                'code' => '51',
            ],
            [
                'name' => 'Aruba',
                'initials' => 'AW',
                'initials_three' => 'ABW',
                'code' => '533',
            ],
            [
                'name' => 'Austrália',
                'initials' => 'AU',
                'initials_three' => 'AUS',
                'code' => '036',
            ],
            [
                'name' => 'Áustria',
                'initials' => 'AT',
                'initials_three' => 'AUT',
                'code' => '040',
            ],
            [
                'name' => 'Azerbaijão',
                'initials' => 'AZ  ',
                'initials_three' => 'AZE',
                'code' => '31',
            ],
            [
                'name' => 'Bahamas',
                'initials' => 'BS',
                'initials_three' => 'BHS',
                'code' => '044',
            ],
            [
                'name' => 'Bahrein',
                'initials' => 'BH',
                'initials_three' => 'BHR',
                'code' => '048',
            ],
            [
                'name' => 'Bangladesh',
                'initials' => 'BD',
                'initials_three' => 'BGD',
                'code' => '050',
            ],
            [
                'name' => 'Barbados',
                'initials' => 'BB',
                'initials_three' => 'BRB',
                'code' => '052',
            ],
            [
                'name' => 'Belarus',
                'initials' => 'BY',
                'initials_three' => 'BLR',
                'code' => '112',
            ],
            [
                'name' => 'Bélgica',
                'initials' => 'BE',
                'initials_three' => 'BEL',
                'code' => '056',
            ],
            [
                'name' => 'Belize',
                'initials' => 'BZ',
                'initials_three' => 'BLZ',
                'code' => '084',
            ],
            [
                'name' => 'Benin',
                'initials' => 'BJ',
                'initials_three' => 'BEN',
                'code' => '204',
            ],
            [
                'name' => 'Bermudas',
                'initials' => 'BM',
                'initials_three' => 'BMU',
                'code' => '060',
            ],
            [
                'name' => 'Bolívia',
                'initials' => 'BO',
                'initials_three' => 'BOL',
                'code' => '068',
            ],
            [
                'name' => 'Bósnia-Herzegóvina',
                'initials' => 'BA',
                'initials_three' => 'BIH',
                'code' => '070',
            ],
            [
                'name' => 'Botsuana',
                'initials' => 'BW',
                'initials_three' => 'BWA',
                'code' => '072',
            ],
            [
                'name' => 'Brasil',
                'initials' => 'BR',
                'initials_three' => 'BRA',
                'code' => '076',
            ],
            [
                'name' => 'Brunei',
                'initials' => 'BN',
                'initials_three' => 'BRN',
                'code' => '096',
            ],
            [
                'name' => 'Bulgária',
                'initials' => 'BG',
                'initials_three' => 'BGR',
                'code' => '100',
            ],
            [
                'name' => 'Burkina Fasso',
                'initials' => 'BF',
                'initials_three' => 'BFA',
                'code' => '854',
            ],
            [
                'name' => 'Burundi',
                'initials' => 'BI',
                'initials_three' => 'BDI',
                'code' => '108',
            ],
            [
                'name' => 'Butão',
                'initials' => 'BT',
                'initials_three' => 'BTN',
                'code' => '064',
            ],
            [
                'name' => 'Cabo Verde',
                'initials' => 'CV',
                'initials_three' => 'CPV',
                'code' => '132',
            ],
            [
                'name' => 'Camarões',
                'initials' => 'CM',
                'initials_three' => 'CMR',
                'code' => '120',
            ],
            [
                'name' => 'Camboja',
                'initials' => 'KH',
                'initials_three' => 'KHM',
                'code' => '116',
            ],
            [
                'name' => 'Canadá',
                'initials' => 'CA',
                'initials_three' => 'CAN',
                'code' => '124',
            ],
            [
                'name' => 'Cazaquistão',
                'initials' => 'KZ',
                'initials_three' => 'KAZ',
                'code' => '398',
            ],
            [
                'name' => 'Chade',
                'initials' => 'TD',
                'initials_three' => 'TCD',
                'code' => '148',
            ],
            [
                'name' => 'Chile',
                'initials' => 'CL',
                'initials_three' => 'CHL',
                'code' => '152',
            ],
            [
                'name' => 'China',
                'initials' => 'CN',
                'initials_three' => 'CHN',
                'code' => '156',
            ],
            [
                'name' => 'Chipre',
                'initials' => 'CY',
                'initials_three' => 'CYP',
                'code' => '196',
            ],
            [
                'name' => 'Cingapura',
                'initials' => 'SG',
                'initials_three' => 'SGP',
                'code' => '702',
            ],
            [
                'name' => 'Colômbia',
                'initials' => 'CO',
                'initials_three' => 'COL',
                'code' => '170',
            ],
            [
                'name' => 'Congo',
                'initials' => 'CG',
                'initials_three' => 'COG',
                'code' => '178',
            ],
            [
                'name' => 'Coréia do Norte',
                'initials' => 'KP',
                'initials_three' => 'PRK',
                'code' => '408',
            ],
            [
                'name' => 'Coréia do Sul',
                'initials' => 'KR',
                'initials_three' => 'KOR',
                'code' => '410',
            ],
            [
                'name' => 'Costa do Marfim',
                'initials' => 'CI',
                'initials_three' => 'CIV',
                'code' => '384',
            ],
            [
                'name' => 'Costa Rica',
                'initials' => 'CR',
                'initials_three' => 'CRI',
                'code' => '188',
            ],
            [
                'name' => 'Croácia (Hrvatska)',
                'initials' => 'HR',
                'initials_three' => 'HRV',
                'code' => '191',
            ],
            [
                'name' => 'Cuba',
                'initials' => 'CU',
                'initials_three' => 'CUB',
                'code' => '192',
            ],
            [
                'name' => 'Dinamarca',
                'initials' => 'DK',
                'initials_three' => 'DNK',
                'code' => '208',
            ],
            [
                'name' => 'Djibuti',
                'initials' => 'DJ',
                'initials_three' => 'DJI',
                'code' => '262',
            ],
            [
                'name' => 'Dominica',
                'initials' => 'DM',
                'initials_three' => 'DMA',
                'code' => '212',
            ],
            [
                'name' => 'Egito',
                'initials' => 'EG',
                'initials_three' => 'EGY',
                'code' => '818',
            ],
            [
                'name' => 'El Salvador',
                'initials' => 'SV',
                'initials_three' => 'SLV',
                'code' => '222',
            ],
            [
                'name' => 'Emirados Árabes Unidos',
                'initials' => 'AE',
                'initials_three' => 'ARE',
                'code' => '784',
            ],
            [
                'name' => 'Equador',
                'initials' => 'EC',
                'initials_three' => 'ECU',
                'code' => '218',
            ],
            [
                'name' => 'Eritréia',
                'initials' => 'ER',
                'initials_three' => 'ERI',
                'code' => '232',
            ],
            [
                'name' => 'Eslováquia',
                'initials' => 'SK',
                'initials_three' => 'SVK',
                'code' => '703',
            ],
            [
                'name' => 'Eslovênia',
                'initials' => 'SI',
                'initials_three' => 'SVN',
                'code' => '705',
            ],
            [
                'name' => 'Espanha',
                'initials' => 'ES',
                'initials_three' => 'ESP',
                'code' => '724',
            ],
            [
                'name' => 'Estados Unidos',
                'initials' => 'US',
                'initials_three' => 'USA',
                'code' => '840',
            ],
            [
                'name' => 'Estônia',
                'initials' => 'EE',
                'initials_three' => 'EST',
                'code' => '233',
            ],
            [
                'name' => 'Etiópia',
                'initials' => 'ET',
                'initials_three' => 'ETH',
                'code' => '231',
            ],
            [
                'name' => 'Fiji',
                'initials' => 'FJ',
                'initials_three' => 'FJI',
                'code' => '242',
            ],
            [
                'name' => 'Filipinas',
                'initials' => 'PH',
                'initials_three' => 'PHL',
                'code' => '608',
            ],
            [
                'name' => 'Finlândia',
                'initials' => 'FI',
                'initials_three' => 'FIN',
                'code' => '246',
            ],
            [
                'name' => 'França',
                'initials' => 'FR',
                'initials_three' => 'FRA',
                'code' => '250',
            ],
            [
                'name' => 'Gabão',
                'initials' => 'GA',
                'initials_three' => 'GAB',
                'code' => '266',
            ],
            [
                'name' => 'Gâmbia',
                'initials' => 'GM',
                'initials_three' => 'GMB',
                'code' => '270',
            ],
            [
                'name' => 'Gana',
                'initials' => 'GH',
                'initials_three' => 'GHA',
                'code' => '288',
            ],
            [
                'name' => 'Geórgia',
                'initials' => 'GE',
                'initials_three' => 'GEO',
                'code' => '268',
            ],
            [
                'name' => 'Gibraltar',
                'initials' => 'GI',
                'initials_three' => 'GIB',
                'code' => '292',
            ],
            [
                'name' => 'Grã-Bretanha (Reino Unido, UK)',
                'initials' => 'GB',
                'initials_three' => 'GBR',
                'code' => '826',
            ],
            [
                'name' => 'Granada',
                'initials' => 'GD',
                'initials_three' => 'GRD',
                'code' => '308',
            ],
            [
                'name' => 'Grécia',
                'initials' => 'GR',
                'initials_three' => 'GRC',
                'code' => '300',
            ],
            [
                'name' => 'Groelândia',
                'initials' => 'GL',
                'initials_three' => 'GRL',
                'code' => '304',
            ],
            [
                'name' => 'Guadalupe',
                'initials' => 'GP',
                'initials_three' => 'GLP',
                'code' => '312',
            ],
            [
                'name' => 'Guam (Território dos Estados Unidos)',
                'initials' => 'GU',
                'initials_three' => 'GUM',
                'code' => '316',
            ],
            [
                'name' => 'Guatemala',
                'initials' => 'GT',
                'initials_three' => 'GTM',
                'code' => '320',
            ],
            [
                'name' => 'Guernsey',
                'initials' => 'G',
                'initials_three' => 'GGY',
                'code' => '831',
            ],
            [
                'name' => 'Guiana',
                'initials' => 'GY',
                'initials_three' => 'GUY',
                'code' => '328',
            ],
            [
                'name' => 'Guiana Francesa',
                'initials' => 'GF',
                'initials_three' => 'GUF',
                'code' => '254',
            ],
            [
                'name' => 'Guiné',
                'initials' => 'GN',
                'initials_three' => 'GIN',
                'code' => '324',
            ],
            [
                'name' => 'Guiné Equatorial',
                'initials' => 'GQ',
                'initials_three' => 'GNQ',
                'code' => '226',
            ],
            [
                'name' => 'Guiné-Bissau',
                'initials' => 'GW',
                'initials_three' => 'GNB',
                'code' => '624',
            ],
            [
                'name' => 'Haiti',
                'initials' => 'HT',
                'initials_three' => 'HTI',
                'code' => '332',
            ],
            [
                'name' => 'Holanda',
                'initials' => 'NL',
                'initials_three' => 'NLD',
                'code' => '528',
            ],
            [
                'name' => 'Honduras',
                'initials' => 'HN',
                'initials_three' => 'HND',
                'code' => '340',
            ],
            [
                'name' => 'Hong Kong',
                'initials' => 'HK',
                'initials_three' => 'HKG',
                'code' => '344',
            ],
            [
                'name' => 'Hungria',
                'initials' => 'HU',
                'initials_three' => 'HUN',
                'code' => '348',
            ],
            [
                'name' => 'Iêmen',
                'initials' => 'YE',
                'initials_three' => 'YEM',
                'code' => '887',
            ],
            [
                'name' => 'Ilha Bouvet (Território da Noruega)',
                'initials' => 'BV',
                'initials_three' => 'BVT',
                'code' => '074',
            ],
            [
                'name' => 'Ilha do Homem',
                'initials' => 'IM',
                'initials_three' => 'IMN',
                'code' => '833',
            ],
            [
                'name' => 'Ilha Natal',
                'initials' => 'CX',
                'initials_three' => 'CXR',
                'code' => '162',
            ],
            [
                'name' => 'Ilha Pitcairn',
                'initials' => 'PN',
                'initials_three' => 'PCN',
                'code' => '612',
            ],
            [
                'name' => 'Ilha Reunião',
                'initials' => 'RE',
                'initials_three' => 'REU',
                'code' => '638',
            ],
            [
                'name' => 'Ilhas Aland',
                'initials' => 'AX',
                'initials_three' => 'ALA',
                'code' => '248',
            ],
            [
                'name' => 'Ilhas Cayman',
                'initials' => 'KY',
                'initials_three' => 'CYM',
                'code' => '136',
            ],
            [
                'name' => 'Ilhas Cocos',
                'initials' => 'CC',
                'initials_three' => 'CCK',
                'code' => '166',
            ],
            [
                'name' => 'Ilhas Comores',
                'initials' => 'KM',
                'initials_three' => 'COM',
                'code' => '174',
            ],
            [
                'name' => 'Ilhas Cook',
                'initials' => 'CK',
                'initials_three' => 'COK',
                'code' => '184',
            ],
            [
                'name' => 'Ilhas Faroes',
                'initials' => 'FO',
                'initials_three' => 'FRO',
                'code' => '234',
            ],
            [
                'name' => 'Ilhas Falkland (Malvinas)',
                'initials' => 'FK',
                'initials_three' => 'FLK',
                'code' => '238',
            ],
            [
                'name' => 'Ilhas Geórgia do Sul e Sandwich do Sul',
                'initials' => 'GS',
                'initials_three' => 'SGS',
                'code' => '239',
            ],
            [
                'name' => 'Ilhas Heard e McDonald (Território da Austrália)',
                'initials' => 'HM',
                'initials_three' => 'HMD',
                'code' => '334',
            ],
            [
                'name' => 'Ilhas Marianas do Norte',
                'initials' => 'MP',
                'initials_three' => 'MNP',
                'code' => '580',
            ],
            [
                'name' => 'Ilhas Marshall',
                'initials' => 'MH',
                'initials_three' => 'MHL',
                'code' => '584',
            ],
            [
                'name' => 'Ilhas Menores dos Estados Unidos',
                'initials' => 'UM',
                'initials_three' => 'UMI',
                'code' => '581',
            ],
            [
                'name' => 'Ilhas Norfolk',
                'initials' => 'NF',
                'initials_three' => 'NFK',
                'code' => '574',
            ],
            [
                'name' => 'Ilhas Seychelles',
                'initials' => 'SC',
                'initials_three' => 'SYC',
                'code' => '690',
            ],
            [
                'name' => 'Ilhas Solomão',
                'initials' => 'SB',
                'initials_three' => 'SLB',
                'code' => '090',
            ],
            [
                'name' => 'Ilhas Svalbard e Jan Mayen',
                'initials' => 'SJ',
                'initials_three' => 'SJM',
                'code' => '744',
            ],
            [
                'name' => 'Ilhas Tokelau',
                'initials' => 'TK',
                'initials_three' => 'TKL',
                'code' => '772',
            ],
            [
                'name' => 'Ilhas Turks e Caicos',
                'initials' => 'TC',
                'initials_three' => 'TCA',
                'code' => '796',
            ],
            [
                'name' => 'Ilhas Virgens (Estados Unidos)',
                'initials' => 'VI',
                'initials_three' => 'VIR',
                'code' => '850',
            ],
            [
                'name' => 'Ilhas Virgens (Inglaterra)',
                'initials' => 'VG',
                'initials_three' => 'VGB',
                'code' => '092',
            ],
            [
                'name' => 'Ilhas Wallis e Futuna',
                'initials' => 'WF',
                'initials_three' => 'WLF',
                'code' => '876',
            ],
            [
                'name' => 'índia',
                'initials' => 'IN',
                'initials_three' => 'IND',
                'code' => '356',
            ],
            [
                'name' => 'Indonésia',
                'initials' => 'ID',
                'initials_three' => 'IDN',
                'code' => '360',
            ],
            [
                'name' => 'Irã',
                'initials' => 'IR',
                'initials_three' => 'IRN',
                'code' => '364',
            ],
            [
                'name' => 'Iraque',
                'initials' => 'IQ',
                'initials_three' => 'IRQ',
                'code' => '368',
            ],
            [
                'name' => 'Irlanda',
                'initials' => 'IE',
                'initials_three' => 'IRL',
                'code' => '372',
            ],
            [
                'name' => 'Islândia',
                'initials' => 'IS',
                'initials_three' => 'ISL',
                'code' => '352',
            ],
            [
                'name' => 'Israel',
                'initials' => 'IL',
                'initials_three' => 'ISR',
                'code' => '376',
            ],
            [
                'name' => 'Itália',
                'initials' => 'IT',
                'initials_three' => 'ITA',
                'code' => '380',
            ],
            [
                'name' => 'Jamaica',
                'initials' => 'JM',
                'initials_three' => 'JAM',
                'code' => '388',
            ],
            [
                'name' => 'Japão',
                'initials' => 'JP',
                'initials_three' => 'JPN',
                'code' => '392',
            ],
            [
                'name' => 'Jersey',
                'initials' => 'JE',
                'initials_three' => 'JEY',
                'code' => '832',
            ],
            [
                'name' => 'Jordânia',
                'initials' => 'JO',
                'initials_three' => 'JOR',
                'code' => '400',
            ],
            [
                'name' => 'Kênia',
                'initials' => 'KE',
                'initials_three' => 'KEN',
                'code' => '404',
            ],
            [
                'name' => 'Kiribati',
                'initials' => 'KI',
                'initials_three' => 'KIR',
                'code' => '296',
            ],
            [
                'name' => 'Kuait',
                'initials' => 'KW',
                'initials_three' => 'KWT',
                'code' => '414',
            ],
            [
                'name' => 'Laos',
                'initials' => 'LA',
                'initials_three' => 'LAO',
                'code' => '418',
            ],
            [
                'name' => 'Látvia',
                'initials' => 'LV',
                'initials_three' => 'LVA',
                'code' => '428',
            ],
            [
                'name' => 'Lesoto',
                'initials' => 'LS',
                'initials_three' => 'LSO',
                'code' => '426',
            ],
            [
                'name' => 'Líbano',
                'initials' => 'LB',
                'initials_three' => 'LBN',
                'code' => '422',
            ],
            [
                'name' => 'Libéria',
                'initials' => 'LR',
                'initials_three' => 'LBR',
                'code' => '430',
            ],
            [
                'name' => 'Líbia',
                'initials' => 'LY',
                'initials_three' => 'LBY',
                'code' => '434',
            ],
            [
                'name' => 'Liechtenstein',
                'initials' => 'LI',
                'initials_three' => 'LIE',
                'code' => '438',
            ],
            [
                'name' => 'Lituânia',
                'initials' => 'LT',
                'initials_three' => 'LTU',
                'code' => '440',
            ],
            [
                'name' => 'Luxemburgo',
                'initials' => 'LU',
                'initials_three' => 'LUX',
                'code' => '442',
            ],
            [
                'name' => 'Macau',
                'initials' => 'MO',
                'initials_three' => 'MAC',
                'code' => '446',
            ],
            [
                'name' => 'Macedônia (República Yugoslava)',
                'initials' => 'MK',
                'initials_three' => 'MKD',
                'code' => '807',
            ],
            [
                'name' => 'Madagascar',
                'initials' => 'MG',
                'initials_three' => 'MDG',
                'code' => '450',
            ],
            [
                'name' => 'Malásia',
                'initials' => 'MY',
                'initials_three' => 'MYS',
                'code' => '458',
            ],
            [
                'name' => 'Malaui',
                'initials' => 'MW',
                'initials_three' => 'MWI',
                'code' => '454',
            ],
            [
                'name' => 'Maldivas',
                'initials' => 'MV',
                'initials_three' => 'MDV',
                'code' => '462',
            ],
            [
                'name' => 'Mali',
                'initials' => 'ML',
                'initials_three' => 'MLI',
                'code' => '466',
            ],
            [
                'name' => 'Malta',
                'initials' => 'MT',
                'initials_three' => 'MLT',
                'code' => '470',
            ],
            [
                'name' => 'Marrocos',
                'initials' => 'MA',
                'initials_three' => 'MAR',
                'code' => '504',
            ],
            [
                'name' => 'Martinica',
                'initials' => 'MQ',
                'initials_three' => 'MTQ',
                'code' => '474',
            ],
            [
                'name' => 'Maurício',
                'initials' => 'MU',
                'initials_three' => 'MUS',
                'code' => '480',
            ],
            [
                'name' => 'Mauritânia',
                'initials' => 'MR',
                'initials_three' => 'MRT',
                'code' => '478',
            ],
            [
                'name' => 'Mayotte',
                'initials' => 'YT',
                'initials_three' => 'MYT',
                'code' => '175',
            ],
            [
                'name' => 'México',
                'initials' => 'MX',
                'initials_three' => 'MEX',
                'code' => '484',
            ],
            [
                'name' => 'Micronésia',
                'initials' => 'FM',
                'initials_three' => 'FSM',
                'code' => '583',
            ],
            [
                'name' => 'Moçambique',
                'initials' => 'MZ',
                'initials_three' => 'MOZ',
                'code' => '508',
            ],
            [
                'name' => 'Moldova',
                'initials' => 'MD',
                'initials_three' => 'MDA',
                'code' => '498',
            ],
            [
                'name' => 'Mônaco',
                'initials' => 'MC',
                'initials_three' => 'MCO',
                'code' => '492',
            ],
            [
                'name' => 'Mongólia',
                'initials' => 'MN',
                'initials_three' => 'MNG',
                'code' => '496',
            ],
            [
                'name' => 'Montenegro',
                'initials' => 'ME',
                'initials_three' => 'MNE',
                'code' => '499',
            ],
            [
                'name' => 'Montserrat',
                'initials' => 'MS',
                'initials_three' => 'MSR',
                'code' => '500',
            ],
            [
                'name' => 'Myanma',
                'initials' => 'MM',
                'initials_three' => 'MMR',
                'code' => '104',
            ],
            [
                'name' => 'Namíbia',
                'initials' => 'NA',
                'initials_three' => 'NAM',
                'code' => '516',
            ],
            [
                'name' => 'Nauru',
                'initials' => 'NR',
                'initials_three' => 'NRU',
                'code' => '520',
            ],
            [
                'name' => 'Nepal',
                'initials' => 'NP',
                'initials_three' => 'NPL',
                'code' => '524',
            ],
            [
                'name' => 'Nicarágua',
                'initials' => 'NI',
                'initials_three' => 'NIC',
                'code' => '558',
            ],
            [
                'name' => 'Níger',
                'initials' => 'NE',
                'initials_three' => 'NER',
                'code' => '562',
            ],
            [
                'name' => 'Nigéria',
                'initials' => 'NG',
                'initials_three' => 'NGA',
                'code' => '566',
            ],
            [
                'name' => 'Niue',
                'initials' => 'NU',
                'initials_three' => 'NIU',
                'code' => '570',
            ],
            [
                'name' => 'Noruega',
                'initials' => 'NO',
                'initials_three' => 'NOR',
                'code' => '578',
            ],
            [
                'name' => 'Nova Caledônia',
                'initials' => 'NC',
                'initials_three' => 'NCL',
                'code' => '540',
            ],
            [
                'name' => 'Nova Zelândia',
                'initials' => 'NZ',
                'initials_three' => 'NZL',
                'code' => '554',
            ],
            [
                'name' => 'Omã',
                'initials' => 'OM',
                'initials_three' => 'OMN',
                'code' => '512',
            ],
            [
                'name' => 'Palau',
                'initials' => 'PW',
                'initials_three' => 'PLW',
                'code' => '585',
            ],
            [
                'name' => 'Panamá',
                'initials' => 'PA',
                'initials_three' => 'PAN',
                'code' => '591',
            ],
            [
                'name' => 'Papua-Nova Guiné',
                'initials' => 'PG',
                'initials_three' => 'PNG',
                'code' => '598',
            ],
            [
                'name' => 'Paquistão',
                'initials' => 'PK',
                'initials_three' => 'PAK',
                'code' => '586',
            ],
            [
                'name' => 'Paraguai',
                'initials' => 'PY',
                'initials_three' => 'PRY',
                'code' => '600',
            ],
            [
                'name' => 'Peru',
                'initials' => 'PE',
                'initials_three' => 'PER',
                'code' => '604',
            ],
            [
                'name' => 'Polinésia Francesa',
                'initials' => 'PF',
                'initials_three' => 'PYF',
                'code' => '258',
            ],
            [
                'name' => 'Polônia',
                'initials' => 'PL',
                'initials_three' => 'POL',
                'code' => '616',
            ],
            [
                'name' => 'Porto Rico',
                'initials' => 'PR',
                'initials_three' => 'PRI',
                'code' => '630',
            ],
            [
                'name' => 'Portugal',
                'initials' => 'PT',
                'initials_three' => 'PRT',
                'code' => '620',
            ],
            [
                'name' => 'Qatar',
                'initials' => 'QA',
                'initials_three' => 'QAT',
                'code' => '634',
            ],
            [
                'name' => 'Quirguistão',
                'initials' => 'KG',
                'initials_three' => 'KGZ',
                'code' => '417',
            ],
            [
                'name' => 'República Centro-Africana',
                'initials' => 'CF',
                'initials_three' => 'CAF',
                'code' => '140',
            ],
            [
                'name' => 'República Democrática do Congo',
                'initials' => 'CD',
                'initials_three' => 'COD',
                'code' => '180',
            ],
            [
                'name' => 'República Dominicana',
                'initials' => 'DO',
                'initials_three' => 'DOM',
                'code' => '214',
            ],
            [
                'name' => 'República Tcheca',
                'initials' => 'CZ',
                'initials_three' => 'CZE',
                'code' => '203',
            ],
            [
                'name' => 'Romênia',
                'initials' => 'RO',
                'initials_three' => 'ROM',
                'code' => '642',
            ],
            [
                'name' => 'Ruanda',
                'initials' => 'RW',
                'initials_three' => 'RWA',
                'code' => '646',
            ],
            [
                'name' => 'Rússia (antiga URSS) - Federação Russa',
                'initials' => 'RU',
                'initials_three' => 'RUS',
                'code' => '643',
            ],
            [
                'name' => 'Saara Ocidental',
                'initials' => 'EH',
                'initials_three' => 'ESH',
                'code' => '732',
            ],
            [
                'name' => 'Saint Vincente e Granadinas',
                'initials' => 'VC',
                'initials_three' => 'VCT',
                'code' => '670',
            ],
            [
                'name' => 'Samoa Americana',
                'initials' => 'AS',
                'initials_three' => 'ASM',
                'code' => '016',
            ],
            [
                'name' => 'Samoa Ocidental',
                'initials' => 'WS',
                'initials_three' => 'WSM',
                'code' => '882',
            ],
            [
                'name' => 'San Marino',
                'initials' => 'SM',
                'initials_three' => 'SMR',
                'code' => '674',
            ],
            [
                'name' => 'Santa Helena',
                'initials' => 'SH',
                'initials_three' => 'SHN',
                'code' => '654',
            ],
            [
                'name' => 'Santa Lúcia',
                'initials' => 'LC',
                'initials_three' => 'LCA',
                'code' => '662',
            ],
            [
                'name' => 'São Bartolomeu',
                'initials' => 'BL',
                'initials_three' => 'BLM',
                'code' => '652',
            ],
            [
                'name' => 'São Cristóvão e Névis',
                'initials' => 'KN',
                'initials_three' => 'KNA',
                'code' => '659',
            ],
            [
                'name' => 'São Martim',
                'initials' => 'MF',
                'initials_three' => 'MAF',
                'code' => '663',
            ],
            [
                'name' => 'São Tomé e Príncipe',
                'initials' => 'ST',
                'initials_three' => 'STP',
                'code' => '678',
            ],
            [
                'name' => 'Senegal',
                'initials' => 'SN',
                'initials_three' => 'SEN',
                'code' => '686',
            ],
            [
                'name' => 'Serra Leoa',
                'initials' => 'SL',
                'initials_three' => 'SLE',
                'code' => '694',
            ],
            [
                'name' => 'Sérvia',
                'initials' => 'RS',
                'initials_three' => 'SRB',
                'code' => '688',
            ],
            [
                'name' => 'Síria',
                'initials' => 'SY',
                'initials_three' => 'SYR',
                'code' => '760',
            ],
            [
                'name' => 'Somália',
                'initials' => 'SO',
                'initials_three' => 'SOM',
                'code' => '706',
            ],
            [
                'name' => 'Sri Lanka',
                'initials' => 'LK',
                'initials_three' => 'LKA',
                'code' => '144',
            ],
            [
                'name' => 'St. Pierre and Miquelon',
                'initials' => 'PM',
                'initials_three' => 'SPM',
                'code' => '666',
            ],
            [
                'name' => 'Suazilândia',
                'initials' => 'SZ',
                'initials_three' => 'SWZ',
                'code' => '748',
            ],
            [
                'name' => 'Sudão',
                'initials' => 'SD',
                'initials_three' => 'SDN',
                'code' => '736',
            ],
            [
                'name' => 'Suécia',
                'initials' => 'SE',
                'initials_three' => 'SWE',
                'code' => '752',
            ],
            [
                'name' => 'Suíça',
                'initials' => 'CH',
                'initials_three' => 'CHE',
                'code' => '756',
            ],
            [
                'name' => 'Suriname',
                'initials' => 'SR',
                'initials_three' => 'SUR',
                'code' => '740',
            ],
            [
                'name' => 'Tadjiquistão',
                'initials' => 'TJ',
                'initials_three' => 'TJK',
                'code' => '762',
            ],
            [
                'name' => 'Tailândia',
                'initials' => 'TH',
                'initials_three' => 'THA',
                'code' => '764',
            ],
            [
                'name' => 'Taiwan',
                'initials' => 'TW',
                'initials_three' => 'TWN',
                'code' => '158',
            ],
            [
                'name' => 'Tanzânia',
                'initials' => 'TZ',
                'initials_three' => 'TZA',
                'code' => '834',
            ],
            [
                'name' => 'Território Britânico do Oceano índico',
                'initials' => 'IO',
                'initials_three' => 'IOT',
                'code' => '086',
            ],
            [
                'name' => 'Territórios do Sul da França',
                'initials' => 'TF',
                'initials_three' => 'ATF',
                'code' => '260',
            ],
            [
                'name' => 'Territórios Palestinos Ocupados',
                'initials' => 'PS',
                'initials_three' => 'PSE',
                'code' => '275',
            ],
            [
                'name' => 'Timor Leste',
                'initials' => 'TP',
                'initials_three' => 'TMP',
                'code' => '626',
            ],
            [
                'name' => 'Togo',
                'initials' => 'TG',
                'initials_three' => 'TGO',
                'code' => '768',
            ],
            [
                'name' => 'Tonga',
                'initials' => 'TO',
                'initials_three' => 'TON',
                'code' => '776',
            ],
            [
                'name' => 'Trinidad and Tobago',
                'initials' => 'TT',
                'initials_three' => 'TTO',
                'code' => '780',
            ],
            [
                'name' => 'Tunísia',
                'initials' => 'TN',
                'initials_three' => 'TUN',
                'code' => '788',
            ],
            [
                'name' => 'Turcomenistão',
                'initials' => 'TM',
                'initials_three' => 'TKM',
                'code' => '795',
            ],
            [
                'name' => 'Turquia',
                'initials' => 'TR',
                'initials_three' => 'TUR',
                'code' => '792',
            ],
            [
                'name' => 'Tuvalu',
                'initials' => 'TV',
                'initials_three' => 'TUV',
                'code' => '798',
            ],
            [
                'name' => 'Ucrânia',
                'initials' => 'UA',
                'initials_three' => 'UKR',
                'code' => '804',
            ],
            [
                'name' => 'Uganda',
                'initials' => 'UG',
                'initials_three' => 'UGA',
                'code' => '800',
            ],
            [
                'name' => 'Uruguai',
                'initials' => 'UY',
                'initials_three' => 'URY',
                'code' => '858',
            ],
            [
                'name' => 'Uzbequistão',
                'initials' => 'UZ',
                'initials_three' => 'UZB',
                'code' => '860',
            ],
            [
                'name' => 'Vanuatu',
                'initials' => 'VU',
                'initials_three' => 'VUT',
                'code' => '548',
            ],
            [
                'name' => 'Vaticano',
                'initials' => 'VA',
                'initials_three' => 'VAT',
                'code' => '336',
            ],
            [
                'name' => 'Venezuela',
                'initials' => 'VE',
                'initials_three' => 'VEN',
                'code' => '862',
            ],
            [
                'name' => 'Vietnã',
                'initials' => 'VN',
                'initials_three' => 'VNM',
                'code' => '704',
            ],
            [
                'name' => 'Zâmbia',
                'initials' => 'ZM',
                'initials_three' => 'ZMB',
                'code' => '894',
            ],
            [
                'name' => 'Zimbábue',
                'initials' => 'ZW',
                'initials_three' => 'ZWE',
                'code' => '716',
            ],
        ];

        $model->insertBatch($data);
    }
}
