<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class PermissionSeeder extends Seeder
{
	public function run()
	{
		$model = model('PermissionModel');

    $data = [
      [
        'role'    => 1,
        'name'    => 'Usuários',
        'key'     => 'users',
        'allowed' => true,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 1,
        'name'    => 'Permisões',
        'key'     => 'permissions',
        'allowed' => true,
        'create'  => false,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 1,
        'name'    => 'Funções',
        'key'     => 'roles',
        'allowed' => true,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 1,
        'name'    => 'Endereços',
        'key'     => 'adresses',
        'allowed' => true,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 1,
        'name'    => 'Cidades',
        'key'     => 'cities',
        'allowed' => true,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 1,
        'name'    => 'Estados',
        'key'     => 'states',
        'allowed' => true,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 1,
        'name'    => 'Países',
        'key'     => 'countries',
        'allowed' => true,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 1,
        'name'    => 'Posts',
        'key'     => 'posts',
        'allowed' => true,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 1,
        'name'    => 'Comentários de post',
        'key'     => 'post-comments',
        'allowed' => true,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 1,
        'name'    => 'Tags de post',
        'key'     => 'post-tags',
        'allowed' => true,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 1,
        'name'    => 'Categorias de post',
        'key'     => 'post-categories',
        'allowed' => true,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 1,
        'name'    => 'Categorias do post',
        'key'     => 'post-has-categories',
        'allowed' => true,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 1,
        'name'    => 'Tags do post',
        'key'     => 'post-has-tags',
        'allowed' => true,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 1,
        'name'    => 'Imagens do post',
        'key'     => 'post-has-images',
        'allowed' => true,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 1,
        'name'    => 'Empresa',
        'key'     => 'company',
        'allowed' => true,
        'create'  => false,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 1,
        'name'    => 'Menus',
        'key'     => 'menus',
        'allowed' => true,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 1,
        'name'    => 'Páginas do menu',
        'key'     => 'menu-pages',
        'allowed' => true,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 1,
        'name'    => 'Widgets',
        'key'     => 'widgets',
        'allowed' => true,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 2,
        'name'    => 'Usuários',
        'key'     => 'users',
        'allowed' => true,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 2,
        'name'    => 'Permisões',
        'key'     => 'permissions',
        'allowed' => true,
        'create'  => false,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 2,
        'name'    => 'Funções',
        'key'     => 'roles',
        'allowed' => false,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 2,
        'name'    => 'Endereços',
        'key'     => 'adresses',
        'allowed' => true,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 2,
        'name'    => 'Cidades',
        'key'     => 'cities',
        'allowed' => true,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 2,
        'name'    => 'Estados',
        'key'     => 'states',
        'allowed' => false,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 2,
        'name'    => 'Países',
        'key'     => 'countries',
        'allowed' => false,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 2,
        'name'    => 'Posts',
        'key'     => 'posts',
        'allowed' => true,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 2,
        'name'    => 'Comentários de post',
        'key'     => 'post-comments',
        'allowed' => true,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 2,
        'name'    => 'Tags de post',
        'key'     => 'post-tags',
        'allowed' => true,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 2,
        'name'    => 'Categorias de post',
        'key'     => 'post-categories',
        'allowed' => true,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 2,
        'name'    => 'Categorias do post',
        'key'     => 'post-has-categories',
        'allowed' => true,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 2,
        'name'    => 'Tags do post',
        'key'     => 'post-has-tags',
        'allowed' => true,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 2,
        'name'    => 'Imagens do post',
        'key'     => 'post-has-images',
        'allowed' => true,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 2,
        'name'    => 'Empresa',
        'key'     => 'company',
        'allowed' => true,
        'create'  => false,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 2,
        'name'    => 'Menus',
        'key'     => 'menus',
        'allowed' => true,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 2,
        'name'    => 'Páginas do menu',
        'key'     => 'menu-pages',
        'allowed' => true,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 2,
        'name'    => 'Widgets',
        'key'     => 'widgets',
        'allowed' => true,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 3,
        'name'    => 'Usuários',
        'key'     => 'users',
        'allowed' => false,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 3,
        'name'    => 'Permisões',
        'key'     => 'permissions',
        'allowed' => false,
        'create'  => false,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 3,
        'name'    => 'Funções',
        'key'     => 'roles',
        'allowed' => false,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 3,
        'name'    => 'Endereços',
        'key'     => 'adresses',
        'allowed' => false,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 3,
        'name'    => 'Cidades',
        'key'     => 'cities',
        'allowed' => false,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 3,
        'name'    => 'Estados',
        'key'     => 'states',
        'allowed' => false,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 3,
        'name'    => 'Países',
        'key'     => 'countries',
        'allowed' => false,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 3,
        'name'    => 'Posts',
        'key'     => 'posts',
        'allowed' => true,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 3,
        'name'    => 'Comentários de post',
        'key'     => 'post-comments',
        'allowed' => true,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 3,
        'name'    => 'Tags de post',
        'key'     => 'post-tags',
        'allowed' => true,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 3,
        'name'    => 'Categorias de post',
        'key'     => 'post-categories',
        'allowed' => true,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 3,
        'name'    => 'Categorias do post',
        'key'     => 'post-has-categories',
        'allowed' => true,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 3,
        'name'    => 'Tags do post',
        'key'     => 'post-has-tags',
        'allowed' => true,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 3,
        'name'    => 'Imagens do post',
        'key'     => 'post-has-images',
        'allowed' => true,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 3,
        'name'    => 'Empresa',
        'key'     => 'company',
        'allowed' => false,
        'create'  => false,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 3,
        'name'    => 'Menus',
        'key'     => 'menus',
        'allowed' => false,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 3,
        'name'    => 'Páginas do menu',
        'key'     => 'menu-pages',
        'allowed' => false,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 3,
        'name'    => 'Widgets',
        'key'     => 'widgets',
        'allowed' => false,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 4,
        'name'    => 'Usuários',
        'key'     => 'users',
        'allowed' => false,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 4,
        'name'    => 'Permisões',
        'key'     => 'permissions',
        'allowed' => false,
        'create'  => false,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 4,
        'name'    => 'Funções',
        'key'     => 'roles',
        'allowed' => false,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 4,
        'name'    => 'Endereços',
        'key'     => 'adresses',
        'allowed' => false,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 4,
        'name'    => 'Cidades',
        'key'     => 'cities',
        'allowed' => false,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 4,
        'name'    => 'Estados',
        'key'     => 'states',
        'allowed' => false,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 4,
        'name'    => 'Países',
        'key'     => 'countries',
        'allowed' => false,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 4,
        'name'    => 'Posts',
        'key'     => 'posts',
        'allowed' => true,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 4,
        'name'    => 'Comentários de post',
        'key'     => 'post-comments',
        'allowed' => true,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 4,
        'name'    => 'Tags de post',
        'key'     => 'post-tags',
        'allowed' => true,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 4,
        'name'    => 'Categorias de post',
        'key'     => 'post-categories',
        'allowed' => true,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 4,
        'name'    => 'Categorias do post',
        'key'     => 'post-has-categories',
        'allowed' => true,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 4,
        'name'    => 'Tags do post',
        'key'     => 'post-has-tags',
        'allowed' => true,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 4,
        'name'    => 'Imagens do post',
        'key'     => 'post-has-images',
        'allowed' => true,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 4,
        'name'    => 'Empresa',
        'key'     => 'company',
        'allowed' => false,
        'create'  => false,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 4,
        'name'    => 'Menus',
        'key'     => 'menus',
        'allowed' => false,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 4,
        'name'    => 'Páginas do menu',
        'key'     => 'menu-pages',
        'allowed' => false,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
      [
        'role'    => 4,
        'name'    => 'Widgets',
        'key'     => 'widgets',
        'allowed' => false,
        'create'  => true,
        'read'    => true,
        'update'  => true,
        'delete'  => true,
      ],
    ];

    $model->insertBatch($data);
	}
}
